version: "3"


services:
  mariadb:
    image: mariadb:10.8.3
    restart: always
    ports:
      - "3306:3306"
    environment:
      USER_UID: 1000
      USER_GID: 1000
      MARIADB_USER: default
      MARIADB_PASSWORD: admin
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - ./mariadb:/var/lib/mysql
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      DB_SERVER: mariadb
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin

      PS_DOMAIN: localhost
      PS_ERASE_DB: 1
      PS_DEMO_MODE: 0
      PS_LANGUAGE: pl
      PS_COUNTRY: pl
      PS_FOLDER_ADMIN: admin-dev
      PS_FOLDER_INSTALL: install-dev
      PS_INSTALL_AUTO: 1
      PS_ENABLE_SSL: 1

      ADMIN_MAIL: lampy@bright.pl
      ADMIN_PASSWD: lampybright
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mariadb